version: '3.9'
services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=aiplus
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=aiplus
    expose:
      - 5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network
networks:
  my_network:
    driver: bridge
